name: wifi_connectivity_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #wifi
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  provider: ^6.0.5
  # calendar
  table_calendar: ^3.0.8
  #url
  url_launcher: ^6.1.14
  #webview
  webview_flutter: ^4.2.4
  #uiux
  flutter_toggle_tab: ^1.4.1
   #mapui
#  google_maps_flutter: ^2.5.0
#  flutter_polyline_points: ^2.0.0
  #geofence
#  location: ^5.0.1
#  permission_handler: ^10.2.0
#  background_location: ^0.11.8
#  quantity_input: ^1.0.2
#  geolocator: ^10.0.0
#  workmanager: ^0.5.1
#  flutter_background_service: ^5.0.1
#  flutter_background_service_android: ^6.0.1
#  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/



